version: "3.8"

services:
  scrappedData:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${PSQL_SERVER_PASSWORD}
      POSTGRES_USER: ${PSQL_SERVER_USERNAME}
      POSTGRES_DB: ${PSQL_SERVER_DATABASE}
    volumes:
      - /var/lib/postgresql/data
    networks:
      - cosmose

networks:
  cosmose: